### ISSUE TITLE
NullPointerException appears when a database error happen

### ISSUE THREAD

**Issue by ashihaby** [couchbaselabs/cbforest-java#44]
`java.lang.NullPointerException: println needs a message
            at android.util.Log.println_native(Native Method)
            at android.util.Log.e(Log.java:334)
            at com.couchbase.lite.util.SimpleLogger.e(SimpleLogger.java:69)
            at com.couchbase.lite.util.Log.e(Log.java:371)
            at com.couchbase.lite.store.ForestDBStore.add(ForestDBStore.java:816)
            at com.couchbase.lite.Database.put(Database.java:1748)
            at com.couchbase.lite.Database.putRevision(Database.java:1701)
            at com.couchbase.lite.Database.putRevision(Database.java:1692)
            at com.couchbase.lite.Document.putProperties(Document.java:428)
            at com.couchbase.lite.UnsavedRevision.save(UnsavedRevision.java:105)
            at com.couchbase.lite.Document.update(Document.java:289)`

**Comment by ashihaby** [comment]
I have fixed it in this pull request #46
